function simresultszybo = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SIMRESULTSZYBO = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SIMRESULTSZYBO = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  simresultszybo = importfile("C:\Users\z103112\workspace\esp_final_project\Matlab_simulink_converter_control\sim_results_zybo.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Nov-2023 09:54:07

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "u", "y"];%, "x1", "x2", "x3", "x4", "x5", "x6"];
opts.VariableTypes = ["double", "double", "double"];%, "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
simresultszybo = readtable(filename, opts);

end